### ISSUE TITLE
the required type was not found

### ISSUE THREAD

**Issue by njsouthern** [countnazgul/qlBuilder#28]
Hi Stefan,

I know your code is good,  I get a failure  using qse on windows 10.  is there any logging?
I believe my certs are correct 

C:\qlbuilderfiles\qltest\qwe>qlbuilder getscript qse
✖ the required type was not found

config.yml is 

name: qse
  host: '***:4747'     masked
  appId: 663a41b6-fc7a-46f9-8541-955ad149cb8e
  authentication:
    type: certificates
    certLocation: C:\certs

.qlbuilder.yml
qse:
  QLIK_USER: ***\***  masked
  QLIK_PASSWORD: *******  masked
  QLIK_CERTS: C:\certs

Any help greatly appreciated.  This is going to be really useful if I can get this working.

Happy to hep testing

Kind Regards

Neil

**Comment by countnazgul** [comment]
Thanks for the issue. 

It seems that this is a bug in the code. The type in the config is `certificates` but for some reason the code was expecting `cert`. 
I've just pushed changes to the code to expects `certificates` as well. 

So can you please re-install the package (just run `npm install -g qlbuilder` again) and try the command

Let me know if its working for you

**Comment by njsouthern** [comment]
Hi Stefan,

 

I’m now  getting …. 

 

C:\qlbuilderfiles\qltest\NJS2>qlbuilder getscript qse

√ This will overwrite all local files. Are you sure? ... yes

☱ Getting script ..(node:20920) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

 

✖ read ECONNRESET

 

 

Cheers  Neil

**Comment by countnazgul** [comment]
Hi Neil,

the warning about `NODE_TLS_REJECT_UNAUTHORIZED ` can be ignored. Im forcing the code (for now) to ignore self-signed certificates errors (probably have to include it as option)

Not sure about the `ECONNRESET`. Usually this means network issues. Are you sure that port 4747 is accessible/open?

Stefan

**Comment by njsouthern** [comment]
Hi Stefan

 

Yes port 4747 is open

 

You may want to include this in the documentation. 

 

How to check if a server port is open from a client machine, with Telnet. (qlik.com) <https://support.qlik.com/articles/000003505#:~:text=Port%204747%20is%20the%20default%20port%20used%20by,an%20error%2C%20port%204747%20is%20blocked%2C%20see%20below> 

 

Still getting 

 

✖ read ECONNRESET

 

Kind Regards

 

Neil 

 

 

 



-- 
This email has been checked for viruses by AVG.
https://www.avg.com

**Comment by njsouthern** [comment]
Hi Stefan,

 

Please see this article …. https://stackoverflow.com/questions/19810530/how-to-resolve-node-js-http-post-econnreset-error/21043839

 

2 different fixes towards the end of what seems lie a random error message.

 

Hope this is of help

 

Cheers Neil

**Comment by njsouthern** [comment]
> Thanks for the issue.
> 
> It seems that this is a bug in the code. The type in the config is `certificates` but for some reason the code was expecting `cert`.
> I've just pushed changes to the code to expects `certificates` as well.
> 
> So can you please re-install the package (just run `npm install -g qlbuilder` again) and try the command
> 
> Let me know if its working for you

Just Spotted its still bring down + qlbuilder@1.4.0   when I try to run the npm install -g qlbuilder.

Above errors related to 'cert'

**Comment by countnazgul** [comment]
Hi Neil,

yea it was my fault for seeing 1.4.0 as latest version. Just Published beta version of 1.4.2 (install via `npm install -g qlbuilder@beta`

Changes:
* certificate option should be fixed (as far as I can test it)
* new `-d` option (stands for `debug`) can be provided to each command that communicates with Qlik (such as `getscript`, `setscript`, `reload` etc). Providing this option will dump `enigma.js` traffic messages for inspection. I was getting `Socket closed` but realised that enigma can provide more info about the error. In my case I forgot to authenticate and enigma was actually returning `mustAuthenticate: true` but the result message was `Socket closed`. Since there are multiple cases where the socket can be closed I've decided to add this parameter to help identify the issue. The debug logs will be created in `C:\Users\<USERNAME>\qlbuilder` folder. One file per "environment". Each run will append to existing files (in your case it can be `C:\Users\Neil\qlbuilder\qse_traffic.txt`). Example:  `qlbuilder getscript qse -d`
* by default Node will not trust self-signed certificates (it was the other way around before). So you should not see the `NODE_TLS_REJECT_UNAUTHORIZED` warning message. IF ignoring the self-signed certificates is required then `trustAllCerts: true` can be provided in `config.xml`
* new command `qlbuilder vscode` - this command will create `.vscode` folder with `tasks.json` and `settings.json` files that can be used to run tasks from VSCode itself

Stefan
